name: Continuous integration
on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch: # allows manual triggering
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  test-nixpkgs:
    name: Build & Test - Nixpkgs
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=./nixpkgs/default.nix
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            extra-substituters = https://cache.iog.io
      - name: Test
        run: |
          nix-shell --arg docTools false --pure --run '
            set -euo pipefail

            # Works because a remote jdk is selected
            bazel build @@rules_jvm_external~5.1//private/tools/java/com/github/bazelbuild/rules_jvm_external/zip:zip --tool_java_language_version=11 --toolchain_resolution_debug=".*jdk.*"

            # Fails because the local jdk is selected
            bazel build @@rules_jvm_external~5.1//private/tools/java/com/github/bazelbuild/rules_jvm_external/zip:zip --toolchain_resolution_debug=".*jdk.*"
            '
